

export const positions = [
  { key: "accountant", value: "Accountant" },
  { key: "administrativeAssistant", value: "Administrative Assistant" },
  { key: "billingSpecialist", value: "Billing Specialist" },
  { key: "bookkeeper", value: "Bookkeeper" },
  { key: "caregiver", value: "Caregiver" },
  { key: "cashier", value: "Cashier" },
  { key: "cleaner", value: "Cleaner" },
  { key: "concierge", value: "Concierge" },
  { key: "courier", value: "Courier" },
  { key: "customerServiceRep", value: "Customer Service Representative" },
  { key: "dataEntryClerk", value: "Data Entry Clerk" },
  { key: "deliveryDriver", value: "Delivery Driver" },
  { key: "eventStaff", value: "Event Staff" },
  { key: "executiveAssistant", value: "Executive Assistant" },
  { key: "fileClerk", value: "File Clerk" },
  { key: "forkliftOperator", value: "Forklift Operator" },
  { key: "frontDeskAgent", value: "Front Desk Agent" },
  { key: "groundskeeper", value: "Groundskeeper" },
  { key: "hrAssistant", value: "HR Assistant" },
  { key: "hospitalityAssistant", value: "Hospitality Assistant" },
  { key: "inventoryClerk", value: "Inventory Clerk" },
  { key: "janitor", value: "Janitor" },
  { key: "kitchenHelper", value: "Kitchen Helper" },
  { key: "mailroomClerk", value: "Mailroom Clerk" },
  { key: "maintenanceWorker", value: "Maintenance Worker" },
  { key: "officeManager", value: "Office Manager" },
  { key: "packagingOperator", value: "Packaging Operator" },
  { key: "payrollClerk", value: "Payroll Clerk" },
  { key: "personalAssistant", value: "Personal Assistant" },
  { key: "purchasingAssistant", value: "Purchasing Assistant" },
  { key: "receptionist", value: "Receptionist" },
  { key: "retailSalesAssociate", value: "Retail Sales Associate" },
  { key: "scheduler", value: "Scheduler" },
  { key: "securityGuard", value: "Security Guard" },
  { key: "stockClerk", value: "Stock Clerk" },
  { key: "storeManager", value: "Store Manager" },
  { key: "ticketAgent", value: "Ticket Agent" },
  { key: "warehouseAssociate", value: "Warehouse Associate" },
  { key: "warehouseHelper", value: "Warehouse Helper" }
];


